# Find all the available rules by running: swiftlint rules

disabled_rules:
  - line_length
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_spacing
  - overridden_super_call

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

reporter: "xcode"
